---
- name: playbook_3
  hosts: all
  become: yes
  vars: 
    pkgname: nginx
  tasks:
    - name: Install nginx on ubuntu
      action: apt name='{{pkgname}}' state=latest

#      OR

#- name: playbook_3
# hosts: all
# become: yes
# tasks:
#        - name: install nginx service
#          apt:
#                name: nginx
#                state: latest