---
- name: playbook_2
  hosts: localhost
  vars:
    URL: cloudblitzy.in
  
  tasks:
      - name: print message_1
        debug: 
          msg: "{{URL}}"

  vars:
    URL: Local.cloudblitzy.in

  vars_files: URL.yml
