- name: playbook_2
  hosts: all
  gather_facts: no
  tasks:

    - name: Print the task_0
      debug:
        msg: "{{ansible_selinux_python_present}}"
      tags: zero


    - name: Print the task_1
      debug:
        msg: "web server"
      tags: one

    - name: Print the task_2
      debug:
        msg: "db server"
      tags: two

    - name: Print the task_3
      debug:
        msg: "my server"
      tags: three