- name: playbook
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
      - name: Install httpd
        yum:
            name: httpd
            state: present
      
      - name: index.html
        copy:
           content: <h1>This is my ansible page</h1>
           dest: /var/www/html/index.html

      - name: restart httpd
        service:
           name: httpd
           state: restarted
           enabled: yes

      

