---
- name: playbook
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
        - name: print the host details_2
          debug:
            msg: "ansible_system_vendor: {{ansible_system_vendor}}"
          when: ansible_system_vendor == "Xen"

        - name: print the host details_3
          debug: 
            msg: "ansible_distribution: {{ansible_distribution}}"
          when: ansible_distribution == "Ubuntu"


