---
# tasks file for tomcat_srv

- name: download Openjdk
  apt:
          name: "{{item}}"
          state: present
  loop:
          - default-jre
          - unzip

- name: download tomcat
  get_url:
          url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz
          dest: /mnt

- name: unzip the tomcat file
  command: tar -xvzf /mnt/apache-tomcat-8.5.81.tar.gz -C /mnt

- name: move student.wab into webapps
  copy:
      src: /home/ubuntu/student.war
      dest: /mnt/apache-tomcat-8.5.81/webapps

- name: start tomcat services
  shell: nohup /mnt/apache-tomcat-8.5.81/bin/catalina.sh start
